server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: AppUser
              uri: lb://AppUser
              predicates:
                - Path=/api/v1/users/**

            - id: Registration
              uri: lb://AppUser
              predicates:
                - Path=/api/v1/registration/**

            - id: Auth
              uri: lb://Auth
              predicates:
                - Path=/api/v1/auth/**

            - id: Reservations
              uri: lb://Reservations
              predicates:
                - Path=/api/v1/reservations/**

            - id: Spaces
              uri: lb://Spaces
              predicates:
                - Path=/api/v1/spaces/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
